apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::148000812951:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-C9HbtZVAUNX7
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::148000812951:user/jenkins
      username: jenkins
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-27T04:34:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1299"
  uid: 9991e0b1-06da-4623-8a23-10ef2245b7c5
