name: solar system
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - features
env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  unit_testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Node JS Setups
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.nodejs_version}}

      - name: Install Dependencies
        run: npm install

      - name: Unit testing
        run: npm test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Result-${{ matrix.nodejs_version }}-${{ matrix.os }}
          path: test-results.xml

  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Node JS Setups
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 1
