name: solar system
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - features
env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  #Unit testing
  unit_testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Node JS Setups
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.nodejs_version}}
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: .node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Unit testing
        run: npm test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Result-${{ matrix.nodejs_version }}-${{ matrix.os }}
          path: test-results.xml

  #Code Coverage
  code_coverage:
    name: Code Coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: node:18
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        options: --name mongo
    env:
      MONGO_URI: "mongodb://mongo:27017/superData"
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password
    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage
        id: node-code-coverage
      #  continue-on-error: true

      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 1
        if: failure() || steps.node-code-coverage.outcome == 'failure' || steps.node-code-coverage.outcome == 'success'

  #Docker Image
  docker_image:
    runs-on: ubuntu-latest
    needs: [code_coverage, unit_testing]
    #needs: []
    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker Image Check
        run: |
          docker images
          docker run --rm --name solar-system -d \
            -p 3000:3000 \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}


          echo "Testing image URL"
          wget -q -O - 127.0.0.1:3000/live | grep live
          echo "Stopping the container"
          docker stop solar-system

      - name: Docker Image push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

  #Development Deploy
  dev_deploy:
    if: github.ref == 'refs/heads/features'
    environment:
      name: Dev
      url: http://${{steps.fetch-alb.outputs.APP_URL}}
    runs-on: ubuntu-latest
    needs: [docker_image]
    outputs:
      APP_URL: ${{steps.fetch-alb.outputs.APP_URL}}
    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: installing kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubectl Config update
        run: |
          aws eks update-kubeconfig --name eksdemo1
          cat ~/.kube/config

      - name: Replace placeholders
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "_{_"
          tokenSuffix: "_}_"
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{vars.NAMESPACE}}
          REPLICAS: ${{vars.REPLICAS}}
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Creating secret
        run: |
          kubectl create ns ${{vars.NAMESPACE}} --dry-run -o yaml | kubectl apply -f -
          kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI="${MONGO_URI}" \
          --from-literal=MONGO_USERNAME="${MONGO_USERNAME}" \
          --from-literal=MONGO_PASSWORD="${MONGO_PASSWORD}" \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: deploying to DEV Env
        run: kubectl apply -f kubernetes/development

      - name: Fetching LB Address
        id: fetch-alb
        run: |
          sleep 10s
          echo "APP_URL= $(kubectl -n ${{vars.NAMESPACE}} get ingress solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_OUTPUT

  #Development Deploy Testing
  dev_deploy_testing:
    if: github.ref == 'refs/heads/features'
    runs-on: ubuntu-latest
    needs: [dev_deploy]
    steps:
      - name: Testing Endpoint
        env:
          URL: ${{needs.dev_deploy.outputs.APP_URL}}
        run: |
          echo $URL
          curl http://$URL/live | grep -i live

  #Production Deploy
  prod_deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: Prod
      url: http://${{steps.fetch-alb.outputs.APP_URL}}
    runs-on: ubuntu-latest
    needs: [docker_image]
    outputs:
      APP_URL: ${{steps.fetch-alb.outputs.APP_URL}}
    steps:
      - name: Checkout Registry
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: installing kubectl
        uses: azure/setup-kubectl@v4

      - name: Kubectl Config update
        run: |
          aws eks update-kubeconfig --name eksdemo1
          cat ~/.kube/config

      - name: Replace placeholders
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "_{_"
          tokenSuffix: "_}_"
          files: '["kubernetes/production/*.yaml"]'
        env:
          NAMESPACE: ${{vars.NAMESPACE}}
          REPLICAS: ${{vars.REPLICAS}}
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Creating secret
        run: |
          kubectl create ns ${{vars.NAMESPACE}} --dry-run -o yaml | kubectl apply -f -
          kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI="${MONGO_URI}" \
          --from-literal=MONGO_USERNAME="${MONGO_USERNAME}" \
          --from-literal=MONGO_PASSWORD="${MONGO_PASSWORD}" \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: deploying to Prod Env
        run: kubectl apply -f kubernetes/production

      - name: Fetching LB Address
        id: fetch-alb
        run: |
          sleep 10s
          echo "APP_URL= $(kubectl -n ${{vars.NAMESPACE}} get ingress solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_OUTPUT

  #Production Deploy Testing
  prod_deploy_testing:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [prod_deploy]
    steps:
      - name: Testing Endpoint
        env:
          URL: ${{needs.prod_deploy.outputs.APP_URL}}
        run: |
          echo $URL
          curl http://$URL/live | grep -i live
